name: App CI/CD

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Build Docker Image
      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-demo ./node-app

      # Login DockerHub
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Push Image
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-demo

      # Deploy to EC2
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/devops-demo:latest

            sudo docker stop app || true
            sudo docker rm app || true

            sudo docker run -d -p 80:3000 --name app ${{ secrets.DOCKER_USERNAME }}/devops-demo:latest

            # Create prometheus.yml
            cat <<EOF > prometheus.yml
            global:
              scrape_interval: 5s
            scrape_configs:
              - job_name: "prometheus"
                static_configs:
                  - targets: ["localhost:9090"]
              - job_name: "app"
                static_configs:
                  - targets: ["localhost:80"]
            EOF

            # Restart Prometheus with config
            sudo docker stop prometheus || true
            sudo docker rm prometheus || true

            sudo docker run -d -p 9090:9090 --name prometheus -v $(pwd)/prometheus.yml:/etc/prometheus/prometheus.yml --name prometheus prom/prometheus
            sudo docker run -d -p 3001:3000 --name grafana grafana/grafana

            sudo docker ps